jobs:
    include:
      -
        name: Ubuntu 18.04
        dist: bionic
        language: python
        python:
          - "3.6"
        cache:
          directories:
            - "~/.platformio"
        install:
          - pip install -U platformio
          - platformio update
        script:
          # Test builds status
          - platformio run -e hw_v2_stm32f042f6_usb
          - platformio run -e hw_v2_dev_stm32f072cb_usb
          - platformio run -e hw_v1_stm32f103c8
          # Run tests
          - platformio test -e test_native
      -
        #if: branch = ignore_all_until_travis_fixed
        name: macOS 10.14
        os: osx
        osx_image: xcode11.3
        language: shell
        cache:
          directories:
            - "~/.platformio"
        install:
          - pip install -U platformio
          - platformio update
        script:
          # Test builds status
          - platformio run -e hw_v2_stm32f042f6_usb
          - platformio run -e hw_v2_dev_stm32f072cb_usb
          - platformio run -e hw_v1_stm32f103c8
      -
        name: Windows
        os: windows           # Windows 10.0.17134 N/A Build 17134
        language: shell
        before_install:
          - choco install python --version 3.6.8
          - python -m pip install --upgrade pip
        env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
        install:
          - pip install -U platformio
          - platformio update
        script:
          # Test builds status
          - platformio run -e hw_v2_stm32f042f6_usb
          - platformio run -e hw_v2_dev_stm32f072cb_usb
          - platformio run -e hw_v1_stm32f103c8
